### ISSUE TITLE
"Open Working Directory" menu option

### ISSUE THREAD

**Issue by LunaNeumeister** [dragondropteam/desktop#17]
**Is your feature request related to a problem? Please describe.**
Relates to #16 , short term mediation

**Describe the solution you'd like**
Currently opening the temporary working directory is limited to loaded projects, and development builds. Add an option to open the general temporary directory until a long term solution is implemented

**Describe alternatives you've considered**
Longer term solutions, new file format, automated backup

**Comment by aeonwilliams** [comment]
PR created.
